Pull request #2161: FL-10171: update www-client/thunderbird to latest release version 102.0.1
Merge in CORE/kit-fixups from ~BORISP/kit-fixups:thunderbird to master

Squashed commit of the following:

commit 214bea91bc5d33a7f7922379c4580de9f45703d2
Author: borisp <boris.pigin@gmail.com>
Date:   Mon Jul 11 22:14:22 2022 +0200

    FL-10171: thunderbird-102.0.1 disable system-icu for using bundled, as thunderbird-102.0.1 needs >=dev-libs/icu-71.1 and funtoo does have 69.1 at the moment and the update to 71.1 should be enjoyed with caution see FL-10175

commit e67edefa777d64ede4230a366e3d4a4d0bdb32cc
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 13:15:59 2022 +0200

    FL-10171: thunderbird-102.0.1 preventing "DAV1DDecoder.cpp:40:12: error: no member named 'n_threads' in 'Dav1dSettings'"

commit 9c97e6c1390a1f887329ba4094bd74d4a73dae87
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 11:53:18 2022 +0200

    FL-10171: thunderbird-102.0.1 GDK_BACKEND

commit b7df9c6a99d726415f13fb1e0f7ff02b8da07375
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 11:52:37 2022 +0200

    FL-10171: thunderbird-102.0.1 python compat

commit 4a5c4b7fc6bd8b8aa850b2b4c5d64c5263b5b147
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 10:51:24 2022 +0200

    FL-10171: thunderbird-102.0.1 preventing "ERROR: --with-system-libevent=PATH is not supported anymore. Please use --with-system-libevent and set any necessary pkg-config environment variable."

commit 21d9b6f3896fdc264fb89845cf5c847fdd5adfc3
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 09:48:46 2022 +0200

    FL-10171: thunderbird-102.0.1 preventing "ERROR: Cannot find a wasi sysroot. Please give its location with --with-wasi-sysroot. Or build with --without-wasm-sandboxed-libraries."

commit 1a42fb9ef69a79067f8d20943e35080b6f35f2e0
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 09:43:39 2022 +0200

    FL-10171: thunderbird-102.0.1 libaom as BDEPEND

commit 96a127edc7f9d410dc49c08d7563c4e1d5554534
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 09:42:23 2022 +0200

    FL-10171: thunderbird-102.0.1 0033-bgo-835788-dav1d-1.0.0-support.patch not found

commit 5aebe34082de8b6cd82339333cb718c8df68952a
Author: borisp <boris.pigin@gmail.com>
Date:   Sat Jul 9 09:38:20 2022 +0200

    FL-10171: thunderbird-102.0.1 initial